Диктант про тестирование
bevzuk/technical-excellence-101 pull request #13
Opened 2023-06-30 06:45 UTC by bevzuk

2023-06-30 06:53 UTC, rin-lazorin requested changes

2023-06-30 06:53 UTC, rin-lazorin commented on README.md
> +Курс про техническое совершенство для нетехнарей (скрам мастеров, владельцев продукта, бизнес аналитиков и т.д.).
Ай молодца

2023-06-30 06:53 UTC, rin-lazorin commented on Unit 3. Code Review & Pair Work/dictation.md
> +Профессиональные разработчики тестируют свой код Однако тестирование не сводится к написанию нескольких модулей или приемочных тестов
Точки нет на концах предложений. Нет запятой после "однако".

2023-06-30 06:53 UTC, rin-lazorin commented on Unit 3. Code Review & Pair Work/dictation.md
> +Описание этих тестов дело полезное но одних не достаточное Проффесиональной группе разработчиков
Нет запятой перед "но". 
Пропущено слово, добавь. 
Одна "ф" в слове "профессиональной".

2023-06-30 06:54 UTC, bevzuk commented on README.md
> +Курс про техническое совершенство для нетехнарей (скрам мастеров, владельцев продукта, бизнес аналитиков и т.д.).
Спасибо, оч приятно ❤️

2023-06-30 06:57 UTC, bevzuk commented on Unit 3. Code Review & Pair Work/dictation.md
> +Профессиональные разработчики тестируют свой код Однако тестирование не сводится к написанию нескольких модулей или приемочных тестов
Исправил, спасибо что заметила.

2023-06-30 06:59 UTC, bevzuk commented on Unit 3. Code Review & Pair Work/dictation.md
> +Описание этих тестов дело полезное но одних не достаточное Проффесиональной группе разработчиков
Сделаю завтра

2023-07-05 15:53 UTC, rin-lazorin commented on Unit 3. Code Review & Pair Work/dictation.md
> +Все участники проекта от начальников до програмистов от секретарей до администраторов баз данных пытались вызвать сбой в программе и им присуждали призы
После "все участники проекта" скорее всего двоеточие.

Поставь запятую перед "от секретарей".

2023-07-05 16:02 UTC, rin-lazorin commented on Unit 3. Code Review & Pair Work/dictation.md
> +Я уже говорил это прежде и скажу снова не смотря что в вашей компании может быть существовать отдельная группа контроля качества занимающияся тестированием продукта группа контроля качества
Предложение не закончено по смыслу, в конце чего-то не хватает и смысл не считывается. Несколько раз повторяется "группа контроля качества", возможно зря.  

По грамматике: 
После "скажу снова" скорее всего нужно двоеточие. 

"Несмотря" слитно, так как выполняет функцию предлога, а не деепричастного оборота. 

Скорее всего, ты хотел написать: "несмотря на то, что в...". Убедись, что есть все предлоги, указательные местоимения и запятая. 

"Занимающиеся" не в множественном числе, а в единственном: "занимающаяся". И запятую до причастия поставь, пожалуйста.

2023-07-05 16:05 UTC, rin-lazorin commented on Unit 3. Code Review & Pair Work/dictation.md
> +Каждый раз когда группа контроля качества что либо обнаруживает это должно стать тревожным сигналом для разработчиков они должны принять меры.
После "каждый раз" нужна запятая. Вот похожий кейс: https://znanija.com/task/34667236

"что-либо" через дефис 

После "обнаруживает" должно быть либо тире, либо запятая. Уточни, пожалуйста. 

После "разработчиков" нужна запятая.

2023-07-07 05:37 UTC, bevzuk commented on README.md
>  Этот курс представлят из себя серию воркшопов, при помощи которых можно объяснить смысл основных инженерных практик даже тем, кто в жизни не написал ни одной строчки кода. Это могут быть владельцы пр
Single comment

2023-07-07 05:48 UTC, rin-lazorin approved these changes
Класс, спасибо

2023-07-07 05:48 UTC, merged